default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coffee_shop_development
  username: <%= ENV['PG_DB_NAME'] %>
  password: <%= ENV['PG_DB_USERNAME'] %>

test:
  <<: *default
  database: coffee_shop_test
  username: <%= ENV['PG_DB_NAME'] %>
  password: <%= ENV['PG_DB_USERNAME'] %>

production:
  <<: *default
  database: coffee_shop_production
  username: <%= ENV['PG_DB_NAME'] %>
  password: <%= ENV['PG_DB_USERNAME'] %>
